# Generated by Django 5.2.14 on 2026-06-17 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stableapp', '0002_perguntafrequente'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='disciplina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='stableapp.disciplina'),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='stableapp.chat'),
        ),
    ]
