# Generated by Django 6.0.5 on 2026-06-03 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stableapp', '0002_chat_mensagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoria',
            name='horario',
            field=models.CharField(default='23h - 00h', max_length=50),
        ),
    ]
