# Generated by Django 6.0.5 on 2026-06-03 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stableapp', '0002_chat_mensagem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inscricaoturma',
            options={},
        ),
        migrations.RemoveField(
            model_name='inscricaoturma',
            name='concluida',
        ),
        migrations.AddField(
            model_name='ctcestudosuser',
            name='is_monitor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inscricaoturma',
            name='status',
            field=models.CharField(choices=[('ATIVA', 'Ativa'), ('CANCELADA', 'Cancelada'), ('CONCLUIDA', 'Concluída')], default='ATIVA', max_length=20),
        ),
    ]
