# Generated by Django 6.0.5 on 2026-06-22 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stableapp', '0003_deck_flashcard'),
        ('stableapp', '0003_mensagem_disciplina_alter_mensagem_chat'),
    ]

    operations = [
    ]
