# Generated by Django 4.2.30 on 2026-06-18 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stableapp', '0003_deck_flashcard'),
        ('stableapp', '0003_mensagem_disciplina_alter_mensagem_chat'),
    ]

    operations = [
    ]
