# Generated by Django 6.0.5 on 2026-06-23 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stableapp', '0003_alter_monitoria_horario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoria',
            name='horario',
            field=models.CharField(default='19h - 21h', max_length=50),
        ),
    ]
