# Generated by Django 6.0.5 on 2026-06-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stableapp', '0003_alter_inscricaoturma_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoria',
            name='dia_semana',
            field=models.CharField(default='sábado', max_length=20),
        ),
        migrations.AddField(
            model_name='monitoria',
            name='horario',
            field=models.CharField(default='19h - 21h', max_length=50),
        ),
        migrations.AddField(
            model_name='monitoria',
            name='link_reuniao',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monitoria',
            name='online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monitoria',
            name='sala',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
