# Generated by Django 5.2.14 on 2026-06-24 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stableapp', '0004_merge_20260622_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duvida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duvidas', to=settings.AUTH_USER_MODEL)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duvidas', to='stableapp.disciplina')),
            ],
            options={
                'verbose_name': 'Dúvida',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='RespostaDuvida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas_duvidas', to=settings.AUTH_USER_MODEL)),
                ('duvida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='stableapp.duvida')),
            ],
            options={
                'verbose_name': 'Resposta',
                'ordering': ['criado_em'],
            },
        ),
    ]
