# Generated by Django 6.0.5 on 2026-06-24 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stableapp', '0005_duvida_respostaduvida'),
    ]

    operations = [
        migrations.AddField(
            model_name='conteudo',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='arquivos_disciplinas/'),
        ),
    ]
