# Generated by Django 6.0.5 on 2026-06-24 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stableapp', '0006_conteudo_arquivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='conteudo',
            name='disciplina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conteudos', to='stableapp.disciplina'),
        ),
        migrations.AlterField(
            model_name='conteudo',
            name='topico',
            field=models.CharField(max_length=100),
        ),
    ]
