# Generated by Django 6.0.5 on 2026-07-01 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stableapp', '0004_merge_20260618_0254'),
        ('stableapp', '0007_conteudo_disciplina_alter_conteudo_topico'),
    ]

    operations = [
    ]
